project:
  type: website
  output-dir: docs

website:
  title: "Agricultural Land Abandonment"
  navbar:
    left:
      - href: index.qmd
        text: Literature Review
      - href: analysis.qmd
        text: Results
      - href: project_progress.qmd
        text: Project Progress Report

# Move global settings here so they apply to both index.qmd AND analysis.qmd
bibliography: references.json
csl: apa.csl
filters:
  - lastmodified.lua

format:
  html:
    theme: darkly
    css: style.css
    toc: true
    toc-location: left
    toc-depth: 3
    code-fold: true
    page-layout: full